### ISSUE TITLE
ERROR during the pip installation process

### ISSUE THREAD

**Issue by lwwlwwl** [marius-team/marius#101]
I was trying to install pip and  

```
ERROR: Could not find a version that satisfies the requirement torch (from marius==0.0.2) (from versions: none)
ERROR: No matching distribution found for torch (from marius==0.0.2)
```
keeps popping up. 

Tried to `pip install torchvision==0.1.8` in command line and it showed `Successfully installed torch-1.11.0 torchvision-0.1.8`. Then, when I tried to `pip3 install .` again, the same error appears. I am wondering how to solve this to proceed. Thank you.

**Comment by lwwlwwl** [comment]
`pip3 install torch` gives the same error. I followed the link trying to install PyTorch via Anaconda, run `pip3 install .` and it gives a new error saying it may not be a problem with pip. 
```
       note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```
torch is installed with v1.10.1

**Comment by JasonMoho** [comment]
Hard to say what's wrong here without more information about your environment. 

What is your:
- Operating system
- pip version 
- python version

**Comment by JasonMoho** [comment]
To get the above information to can run this [script](https://github.com/marius-team/marius/blob/main/src/python/distribution/marius_env_info.py):
`python3 src/python/distribution/marius_env_info.py`

You may have to install importlib_metadata first:
`pip3 install importlib_metadata`

You should see output like the following if all works properly
```
python3 src/python/distribution/marius_env_info.py 
cmake:
  version: 3.21.2
cpu_info:
  num_cpus: 12
  total_memory: 32GB
cuda:
  version: N/A
gpu_info: []
marius:
  bindings_installed: false
  install_path: N/A
  version: N/A
openmp:
  version: N/A
operating_system:
  platform: macOS-11.6-x86_64-i386-64bit
pybind:
  PYBIND11_BUILD_ABI: _cxxabi1002
  PYBIND11_COMPILER_TYPE: _clang
  PYBIND11_STDLIB: _libcpp
python:
  compiler: Clang 13.0.0 (clang-1300.0.29.30)
  deps:
    breathe_version: 4.30.0
    numpy_version: 1.21.2
    omegaconf_version: 2.2.1
    pandas_version: 1.3.3
    pip_version: 22.0.4
    pyspark_version: 3.2.0
    pytest_version: 6.2.5
    sphinx_rtd_theme_version: 1.0.0
    torch_version: !!python/object/new:torch.torch_version.TorchVersion
      - 1.11.0
    tox_version: 3.24.3
  version: 3.9.12
pytorch:
  install_path: /usr/local/lib/python3.9/site-packages/torch
  version: !!python/object/new:torch.torch_version.TorchVersion
    - 1.11.0
```

**Comment by lwwlwwl** [comment]
For some reason `python3 src/python/distribution/marius_env_info.py` gives `ModuleNotFoundError: No module named 'yaml'`. So I ran the script directly and gave the following
```
/bin/sh: cmake: command not found
clang: error: unsupported option '-fopenmp'
cmake:
  version: N/A
cpu_info:
  num_cpus: 2
  total_memory: 8GB
cuda:
  version: N/A
gpu_info: N/A
marius:
  bindings_installed: false
  install_path: N/A
  version: N/A
openmp:
  version: N/A
operating_system:
  platform: macOS-10.16-x86_64-i386-64bit
pybind:
  PYBIND11_BUILD_ABI: _cxxabi1002
  PYBIND11_COMPILER_TYPE: _clang
  PYBIND11_STDLIB: _libcpp
python:
  compiler: 'Clang 10.0.0 '
  deps:
    breathe_version: N/A
    numpy_version: 1.19.2
    omegaconf_version: N/A
    pandas_version: 1.1.3
    pip_version: 20.2.4
    pyspark_version: N/A
    pytest_version: 6.1.1
    sphinx_rtd_theme_version: N/A
    torch_version: !!python/object/new:torch.torch_version.TorchVersion
      - 1.10.1
    tox_version: N/A
  version: 3.8.5
pytorch:
  install_path: /Users/yuchen/opt/anaconda3/lib/python3.8/site-packages/torch
  version: !!python/object/new:torch.torch_version.TorchVersion
    - 1.10.1
```
For cmake here, I installed the extension CMake Tools in vscode but it seems not working.
For Clang, I tried `Clang --version` and it gives 
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
