### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by lwwlwwl** [marius-team/marius#105]
Hi, 

I was trying to run marius on ogbn_products dataset on on gcp vm with following:
CPU: 16 x Intel Haswell
Memory: 60 GB
Storage: 1 x SSD 100 GB
GPU: 1 x NVIDIA Tesla P100
OS: Ubuntu 20.04

I installed and ran marius using docker following [this](https://github.com/marius-team/marius/issues/101#issuecomment-1165116872).

OOM is triggered if all edges, features and embeddings are placed in DEVICE_MEMORY. Then, I tried to use mixed CPU-GPU following this [sample file](http://marius-project.org/marius/config_interface/samples.html#storage-configs) (where I think there may be some inconsistencies between the sample code and the explanation below for mixed CPU-GPU section). However, this triggers a RuntimeError where the error message is 
```
root@7f36de16f004:/marius# marius_train examples/configuration/ogbn_products.yaml
[2022-07-05 15:01:54.234] [info] [marius.cpp:43] Start initialization
[07/05/22 15:02:03.393] Initialization Complete: 9.158s
[07/05/22 15:02:18.924] ################ Starting training epoch 1 ################
Traceback (most recent call last):
  File "/usr/local/bin/marius_train", line 11, in <module>
    load_entry_point('marius==0.0.2', 'console_scripts', 'marius_train')()
  File "/usr/local/lib/python3.6/dist-packages/marius/console_scripts/marius_train.py", line 18, in main
    m.manager.marius_train(config)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument index in method wrapper_index_select)
```

The configuration file is as following:
```
model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    train_neighbor_sampling:
      - type: ALL
      - type: ALL
      - type: ALL
    layers:
      - - type: FEATURE
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 47
          bias: true
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.01
storage:
  device_type: cuda
  dataset:
    dataset_dir: datasets/ogbn_products/
  edges:
    type: HOST_MEMORY
    options:
      dtype: int
  features:
    type: HOST_MEMORY
    options:
      dtype: float
  embeddings:
    type: HOST_MEMORY
    options:
      dtype: float
training:
  batch_size: 100
  num_epochs: 2
  pipeline:
    sync: true
evaluation:
  batch_size: 100
  pipeline:
    sync: true

```

I tried different combinations of setting the type of edges, features and embeddings, but all of them gave the same RuntimeError. 
<img width="630" alt="Screen Shot 2022-07-05 at 11 20 55" src="https://user-images.githubusercontent.com/94249719/177362037-7947cd8e-b175-4436-be46-7c7a3a14abb7.png">

I am wondering how to solve this error to get marius run on ognb_products using gpu. Thank you.

**Comment by rogerwaleffe** [comment]
Hi,

It looks like there may be a few issues with the configuration file. The main issue causing this error I believe is that the `nodes` storage object has not been defined, but is needed for node classification. After adding that (as well as the dataset statistics), my guess however, is that you will run out of GPU memory by using all neighbors for your three layer GNN. Try this configuration file (where I have also switch to asynchronous training for performance, and modified the GNN layers to specify initialization and activations. I also added a few other comments for things you may wish to change. The main one being to increase the batch size for higher throughput).  You should be able to get around 90 percent validation accuracy I would think.

```
model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    train_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    eval_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    layers:
      - - type: FEATURE
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 100
          bias: true
          activation: RELU
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 100
          bias: true
          activation: RELU
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 47
          bias: true
          activation: NONE
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.01 # maybe 0.003
storage:
  device_type: cuda
  dataset:
    dataset_dir: ../Marius2P/datasets/products/
    num_edges: 61859140
    num_nodes: 2449029
    num_relations: 1
    num_train: 196615
    num_valid: 39323
    num_test: 2213091
    feature_dim: 100
    rel_feature_dim: -1
    num_classes: 47
  edges:
    type: HOST_MEMORY
    options:
      dtype: int
  nodes:
    type: HOST_MEMORY
    options:
      dtype: int
  features:
    type: HOST_MEMORY
    options:
      dtype: float
training:
  batch_size: 100 # maybe 1024
  num_epochs: 2 # maybe 10
  pipeline:
    sync: false
evaluation:
  batch_size: 100 # maybe 1024
  pipeline:
    sync: false
```
