### ISSUE TITLE
'test_edges.bin' and 'validation_edges.bin' are not created when preprocess ogbn_products.

### ISSUE THREAD

**Issue by qhtjrmin** [marius-team/marius#110]
Hi,
I want to run marius with ogbn-products dataset.

I executed the following command:
`
marius_preprocess --dataset ogbn_products --output_dir datasets/ogbn_products
`

There was no problem running it, but only 'train_edges.bin' was created in ogbn_products/edges. 
There is no 'test_edges.bin' and 'validation_edges.bin'.
How could I get them?? 

Thanks a lot.

**Comment by rogerwaleffe** [comment]
Thanks for your question. This is actually the expected behavior because [ogbn-products](https://ogb.stanford.edu/docs/nodeprop/#ogbn-products) is a benchmark graph for the task of _node classification_. The goal for this graph is to predict the category of a product (node) in a multi-class classification setup. Thus the nodes in the graph are split into a set of label training nodes, validation nodes, and test nodes, but the edges of the graph are not split in anyway. All edges in the graph are contained in the train_edges.bin file. 

If you would like to run _link prediction_ on the ogbn-products dataset you will need to treat it as a custom graph for link prediction and split the graph edges into random train/val/test edges manually. This can be done as outlined in this [example](http://marius-project.org/marius/examples/config/lp_custom.html). In that example, we use the ogbn-arxiv node classification dataset as a custom graph for link prediction.

**Comment by qhtjrmin** [comment]
Thank you for your rapid reply!

I wanted to perform _node classification_ with this dataset, but I get the following error:

> $ ./marius_train examples/configuration/ogbn_product.yaml
[2022-08-10 02:20:02.722] [info] [marius.cpp:43] Start initialization
file reading error: /home/marius/datasets/ogbn_products/edges/validation_edges.bin
file reading error: /home/marius/datasets/ogbn_products/edges/test_edges.bin

How could I run the marius_train??

**Comment by rogerwaleffe** [comment]
Can you share the ogbn_products.yaml file?

**Comment by qhtjrmin** [comment]
I wanted to try running first, so I used _custom_nc.yaml_ almost as it is.

The following is the current ogbn_products.yaml:
> model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    train_neighbor_sampling:
      - type: ALL
      - type: ALL
      - type: ALL
    layers:
      - - type: FEATURE
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 47
          bias: true
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.01
storage:
  device_type: cuda
  dataset:
    dataset_dir: datasets/ogbn_products
  edges:
    type: DEVICE_MEMORY
    options:
      dtype: int
  features:
    type: DEVICE_MEMORY
    options:
      dtype: float
training:
  batch_size: 1000
  num_epochs: 10
  pipeline:
    sync: true
evaluation:
  batch_size: 1000
  pipeline:
    sync: true

**Comment by rogerwaleffe** [comment]
Nothing immediately jumps out as a problem. However I can't tell if the yaml formatting is correct. Can you also share the full_config.yaml file which is generated in the dataset directory so I can take a look at that?

**Comment by qhtjrmin** [comment]
I can't find full_config.yaml file.
Do you mean dataset.yaml which is generated in the dataset directory??
The following is dataset.yaml: 
> dataset_dir: /home/marius/datasets/ogbn_products/
num_edges: 61859140
num_nodes: 2449029
num_relations: 1
num_train: 196615
num_valid: 39323
num_test: 2213091
node_feature_dim: 100
rel_feature_dim: -1
num_classes: 47
initialized: false

**Comment by rogerwaleffe** [comment]
If you can't find the full_config.yaml file, my guess is that your ogbn_products.yaml has some formatting problems causing the parsing of the config to get messed up. Try this config file (where I have also switched to uniform neighborhood sampling because all neighbors will likely cause a GPU OOM on the products graph). This config file worked for me on the main branch. You can also see another example config for products [here](https://github.com/marius-team/marius/issues/105#issuecomment-1175330468).

```
model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    train_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    eval_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    layers:
      - - type: FEATURE
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 100
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 47
          bias: true
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.01
storage:
  device_type: cuda
  dataset:
    dataset_dir: ../Marius2P/datasets/products/
  edges:
    type: DEVICE_MEMORY
    options:
      dtype: int
  features:
    type: DEVICE_MEMORY
    options:
      dtype: float
training:
  batch_size: 1000
  num_epochs: 10
  pipeline:
    sync: true
evaluation:
  batch_size: 1000
  pipeline:
    sync: true
```
