### ISSUE TITLE
Segmentation Fault in Disk Mode Despite Fix in PR 147

### ISSUE THREAD

**Issue by griii** [marius-team/marius#157]
I am reaching out to report an issue I am encountering with the marius_trian, specifically when using the disk mode. Despite the segmentation fault being addressed in this PR (https://github.com/marius-team/marius/pull/147), I am still experiencing the same problem after updating to the latest version of the project.

It is worth noting that the operation of Marius in memory mode is completely normal. Below are my configurations for Marius preprocessing. 
![图片](https://github.com/marius-team/marius/assets/62171786/f988677b-7490-43ec-914d-7c48f4ba54df)

The following are my disk YAML configurations for marius_train.
```
# examples/configuration/ogbn_paper100m_disk.yaml
model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    train_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 10
    layers:
      - - type: FEATURE
          output_dim: 100
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 100
          output_dim: 256
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 256
          output_dim: 256
          bias: true
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          input_dim: 256
          output_dim: 150
          bias: true
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: SUM
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.01
storage:
  device_type: cuda
  dataset:
    dataset_dir: /data/wb2001/
  edges:
    type: FLAT_FILE
  nodes:
    type: HOST_MEMORY
  features:
    type: PARTITION_BUFFER
    options:
      num_partitions: 16
      buffer_capacity: 5
      prefetching: true
      fine_to_coarse_ratio: 1
      num_cache_partitions: 0
      node_partition_ordering: DISPERSED
  # prefetch: false
  # shuffle_input: true
  # full_graph_evaluation: true
training:
  batch_size: 1000
  num_epochs: 3
  pipeline:
    sync: true
```
