### ISSUE TITLE
ogbn_product.yaml file question

### ISSUE THREAD

**Issue by jk912** [marius-team/marius#161]
Hi! 

I wrote an issue a few months ago if I remember correctly and I am having an issue for training products dataset. 

Is it possible to share the products.yaml file?

I kinda have an issue like below.

`Traceback (most recent call last):
  File "/home/anaconda3/envs/gnn_3/bin/marius_train", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/gnn_3/lib/python3.10/site-packages/marius/console_scripts/marius_train.py", line 22, in main
    m.manager.marius_train(config)
RuntimeError`

And I am using the yaml file attached below. 

It will be nice to see the products.yaml file you guys used for validating... like papers100m!

```
model:
  learning_task: NODE_CLASSIFICATION
  encoder:
    use_incoming_nbrs: true
    use_outgoing_nbrs: true
    train_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
        use_hashmap_sets: true
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    eval_neighbor_sampling:
      - type: UNIFORM
        options:
          max_neighbors: 15
        use_hashmap_sets: true
      - type: UNIFORM
        options:
          max_neighbors: 10
      - type: UNIFORM
        options:
          max_neighbors: 5
    layers:
      - - type: FEATURE
          output_dim: 100
          bias: false
          activation: NONE
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 100
          bias: true
          bias_init:
            type: ZEROS
          activation: RELU
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 100
          bias: true
          bias_init:
            type: ZEROS
          activation: RELU
      - - type: GNN
          options:
            type: GRAPH_SAGE
            aggregator: MEAN
          init:
            type: GLOROT_NORMAL
          input_dim: 100
          output_dim: 47
          bias: true
          bias_init:
            type: ZEROS
          activation: NONE
  decoder:
    type: NODE
  loss:
    type: CROSS_ENTROPY
    options:
      reduction: MEAN
  dense_optimizer:
    type: ADAM
    options:
      learning_rate: 0.003
storage:
  device_type: cuda
  dataset:
    dataset_dir: /home/marius_origin/marius/ogbn_products_example
    num_edges: 61859140
    num_nodes: 2449029
    num_relations: 1
    num_train: 196615
    num_valid: 39323
    num_test: 2213091
    node_feature_dim: 100
    rel_feature_dim: -1
    num_classes: 47
    initialized: false
  edges:
    type: HOST_MEMORY
  nodes:
    type: HOST_MEMORY
  features:
    type: PARTITION_BUFFER
    options:
      num_partitions: 32
      buffer_capacity: 3
      prefetching: true
      fine_to_coarse_ratio: 1
      num_cache_partitions: 0
      node_partition_ordering: DISPERSED
  shuffle_input: true
  full_graph_evaluation: false
  train_edges_pre_sorted: false
training:
  batch_size: 1000
  num_epochs: 3
  pipeline:
    sync: true
  epochs_per_shuffle: 1
  logs_per_epoch: 2
evaluation:
  batch_size: 1000
  pipeline:
    sync: true
  epochs_per_eval: 1
```
